apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://netdata.github.io/helmchart/
    chart: netdata
    targetRevision: "3.7.175"
    helm:
      valuesObject:
        parent: { claiming: { enabled: false } }
        child: { claiming: { enabled: false } }
  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
